### ISSUE TITLE
Compiling the unicycle footstep planner in windows

### ISSUE THREAD

**Issue by mebbaid** [robotology/unicycle-footstep-planner#12]
The following error is met:
![unicycleerror](https://user-images.githubusercontent.com/36491318/40410466-30332c28-5e6e-11e8-91f5-d38b279424a1.JPG)
This is basically due to the `CMakeLists.txt` looking for a `.lib` extensions, because `target_link_libraries` doesn't find the associated `UnicyclePlanner.lib`. One reason would be, I suspect, that the declarative `__declspec(dllexport)` was not used, and hence the project only builds the `.dll` file.

One can instead build the project as a static lib and in that case the above error will not be met, but I am not certain what are the implications of that.

**Comment by traversaro** [comment]
> One reason would be, I suspect, that the declarative __declspec(dllexport) was not used, and hence the project only builds the .dll file.

Exactly. See https://github.com/ros/urdfdom/issues/42 for a similar issue. 

As documented in the  [`how-to-export-cpp-library`](https://github.com/robotology/how-to-export-cpp-library) I suggest to: 
* Use the [`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`](https://github.com/robotology/how-to-export-cpp-library/blob/bc184877b002737d457f773fbbcac3bbef4208d3/CMakeLists.txt#L44) to export all symbols in the shared libraries on Windows (following the same policy used in Linux/macOS for symbol visibility). 
* Do not hardcode the `SHARED` option in the [call to add_library](https://github.com/robotology/unicycle-footstep-planner/blob/master/CMakeLists.txt#L49), but rather leave this unspecified (as in https://github.com/robotology/how-to-export-cpp-library/blob/bc184877b002737d457f773fbbcac3bbef4208d3/src/LibTemplateCMake/CMakeLists.txt#L35) but define the standard CMake option [`BUILD_SHARED_LIBS`](https://github.com/robotology/how-to-export-cpp-library/blob/bc184877b002737d457f773fbbcac3bbef4208d3/CMakeLists.txt#L66) with a default to ON to leave to the user compiling the library the freedom to compile it as shared or static (this is example necessary for packaging the library in vcpkg).

**Comment by traversaro** [comment]
@mebbaid Feel free to open a PR with one or even better both of this changes, that @S-Dafarra can review and eventually accept.

**Comment by mebbaid** [comment]
@traversaro  maybe it is strange, but actually it compiled without errors, without having to remove `shared`
and generated the necessary static libs to link against the .dll objects. an insight into why this is the case would be appreciated.

**Comment by S-Dafarra** [comment]
Solved with https://github.com/robotology/unicycle-footstep-planner/pull/13
