### ISSUE TITLE
How to run DcmInterpolationTest

### ISSUE THREAD

**Issue by dosh1234** [robotology/unicycle-footstep-planner#16]
@GiulioRomualdi A simple question.How can I run DcmInterpolationTest? My steps are as follows:
`cd /unicycle-footstep-planner/build/tests/`
`./DcmInterpolationTest`
But it reminds me that I have no footprint name.
```
[DCM TRAJECTORY GENERATOR] The name of the footprint is neither left nor right. Does iCub have more legs?!
[DCM TRAJECTORY GENERATOR] Unable to get the ZMP Delta.
[FEETINTERPOLATOR] Failed while computing the DCM trajectories.
:-1 : assertTrue failure
```
so I try  
`./DcmInterpolationTest left` 
It doesn't work either.

**Comment by S-Dafarra** [comment]
Hi @dosh1234! The test was bugged. Can you try to pull and run the test again? No arguments are needed.

**Comment by dosh1234** [comment]
Hi @S-Dafarra! Thank you for your changes. After rerunning, everything was fine, and I got three DCM tracks, which helped me understand iCub's walking strategy better. Some theoretical knowledge can be obtained from Johannes Englsberger. Thank you for your works.

**Comment by S-Dafarra** [comment]
Glad to hear that! Thank you!
