### ISSUE TITLE
Unable to find Eigen3 on Windows

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/unicycle-footstep-planner#19]
I'm trying to compile the repository on Windows and seems that the cmake is not able to find `Eigen3`. I think that the problem can be easily solved by adding [`FindEigen3.cmake`](https://github.com/robotology/idyntree/blob/master/cmake/FindEigen3.cmake) in the cmake folder

@S-Dafarra and @traversaro

**Comment by S-Dafarra** [comment]
Thanks! Fixed in https://github.com/robotology/unicycle-footstep-planner/commit/22d6d767d4f07ed5aeffe50c64f9b85bab7847fb

**Comment by traversaro** [comment]
Related discussion: https://github.com/robotology/osqp-eigen/pull/19#issuecomment-460623261 .
