### ISSUE TITLE
Implement a DCM trajectory generator

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/unicycle-footstep-planner#2]
In order to implement a DCM based [controller](https://github.com/loc2/element_capture-point-walking/) a trajectory generator for the Divergent Component Of Motion is needed.

**Comment by GiulioRomualdi** [comment]
The code of the first version of the DCM trajectory generator can be found [here](https://github.com/GiulioRomualdi/unicycle-footstep-planner/tree/DCM_devel). (I think you cannot visualize the repository because it is private, if you want I can create a new branch in this repository and open a pull request)

## Results
The results are collected using the  [`interpolationTest`](../blob/newFeatures/tests/interpolationTest.cpp).
In the figure below the DCM trajectory (both x and y coordinates) is shown. The trajectory generator takes into account both Single and Double Support using an [heuristic technique](http://ieeexplore.ieee.org/document/6943128/). 
![dcm_coordinate](https://user-images.githubusercontent.com/16744101/35054246-5f55876e-fbac-11e7-9108-56c3d7a19b14.png)

## TODO
- [ ] Using `mergePoints` in the generation of the DCM trajectory

**Comment by GiulioRomualdi** [comment]
With the new [release](https://github.com/GiulioRomualdi/unicycle-footstep-planner/tree/DCM_devel) two DCM trajectories can be are merged in the middle of the Double Support phase (`mergePoint`).  
It is important to notice that the _new_ trajectory is evaluated imposing, at the `mergePoint`, the same velocity and position of the _old_ trajectory.   
More formally
![codecogseqn 4](https://user-images.githubusercontent.com/16744101/35213073-b14aaeec-ff5c-11e7-9871-3033caf10729.gif)
where ![codecogseqn 8](https://user-images.githubusercontent.com/16744101/35213086-ba7a329e-ff5c-11e7-98df-fcd9d3fc9739.gif) is the time at the merge point and  ![codecogseqn 6](https://user-images.githubusercontent.com/16744101/35213090-c0f2af34-ff5c-11e7-97da-a8c6f55eac81.gif) is the DCM position.  
It is important to underline that the `mergePoint` approach allows the real-time evaluation of the trajectory (for example using a joystick).  
In the following some result plots (obtained using the new [`DcmInterpolationTest`](https://github.com/GiulioRomualdi/unicycle-footstep-planner/blob/DCM_devel/tests/DcmInterpolationTest.cpp)) are shown. In the first one the _old_ (blue) and the _new merged_ (orange) DCM trajectories are shown
 while in the other figures the x and y coordinate of the DCM trajectories are shown
![dcm_traj](https://user-images.githubusercontent.com/16744101/35213180-088c2ef6-ff5d-11e7-963c-5fe9d3ff3c1d.png)

**Comment by GiulioRomualdi** [comment]
[Here](https://github.com/loc2/element_capture-point-walking/blob/devel_cp_traj/technical-reports/trajectory_generator-report/trajectory_generator-report.pdf) you can find further information about the theory behind the DCM trajectory generator.

**Comment by dosh1234** [comment]
@GiulioRomualdi A simple question.How can I run DcmInterpolationTest? My steps are as follows:
`cd /unicycle-footstep-planner/build/tests/`
`./DcmInterpolationTest`
But it reminds me that I have no footprint name.
```
[DCM TRAJECTORY GENERATOR] The name of the footprint is neither left nor right. Does iCub have more legs?!
[DCM TRAJECTORY GENERATOR] Unable to get the ZMP Delta.
[FEETINTERPOLATOR] Failed while computing the DCM trajectories.
:-1 : assertTrue failure
```
so I try  
`./DcmInterpolationTest left` 
It doesn't work either.
