### ISSUE TITLE
 Add the possibility to disable the pause condition

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/unicycle-footstep-planner#21]
It would be nice to add the possibility to disable the pause condition 

In https://github.com/robotology/unicycle-footstep-planner/pull/20/commits/dadc9927bf8af5f06e1ccd2bee65fd16ec9c41e9 , the problem was faced by adding a flag in the `setPauseConditions()` method. However, if I have to tell the truth I don't like this approach. What do you think to create a new function for enabling or disabling this feature? (i.e. something similar to `addTerminalStep()`)

cc @S-Dafarra

**Comment by S-Dafarra** [comment]
Actually the flag ``pauseActive`` is by default ``false`` (https://github.com/robotology/unicycle-footstep-planner/blob/22d6d767d4f07ed5aeffe50c64f9b85bab7847fb/src/UnicycleGenerator.cpp#L33) and set to ``true`` when calling the [``setPauseConditions``](https://github.com/robotology/unicycle-footstep-planner/blob/22d6d767d4f07ed5aeffe50c64f9b85bab7847fb/src/UnicycleGenerator.cpp#L581) method. It should be enough not to call this method.

**Comment by traversaro** [comment]
I do not have a strong opinion on this particular case, but this article may be interesting: https://abseil.io/tips/94 .

**Comment by GiulioRomualdi** [comment]
As @S-Dafarra explained in https://github.com/robotology/unicycle-footstep-planner/issues/21#issuecomment-480206882  it is already possible to disable the pause condition. Thus we can close this issue.

**Comment by S-Dafarra** [comment]
Feel free to propose a better way to do that anyway :wink:
