### ISSUE TITLE
Add the variable related to the double support ratio for DCM planning (alpha) to the configuration file

### ISSUE THREAD

**Issue by MiladShafiee** [robotology/unicycle-footstep-planner#23]
The variable ($\alpha$) related to the ratio of the double support time that will allocated to previous single support and next single support in DCM planner is not in the configuration files!

**Comment by S-Dafarra** [comment]
Hi @MiladShafiee, sorry for the super late answer. I am not sure I understood your request here. The phases are not decided by the DCM planner, hence I am not sure the parameter you are asking actually exists.

**Comment by MiladShafiee** [comment]
> Hi @MiladShafiee, sorry for the super late answer. I am not sure I understood your request here. The phases are not decided by the DCM planner, hence I am not sure the parameter you are asking actually exists.

Hi @S-Dafarra. If I remember correctly It is related to [this paper](https://ieeexplore.ieee.org/abstract/document/6943128)  that it allocates part of single support for having a double support phase. In this way first they allocate $\alpha * DSTime$ of previous single support and $(1-\alpha) * DSTime$ of the next single support for having an interpolation to find DCM trajectory for double support. I guess we used $\alpha=0.5$ but we could embed this parameter in the configuration file for tuning in some cases.

**Comment by S-Dafarra** [comment]
I think then the parameter you are mentioning already exists. It is the ``switchOverSwingRatio`` which can be set through:
https://github.com/robotology/unicycle-footstep-planner/blob/fd10aae80e244feeba8f8c669181d1cad4e7f9a2/include/UnicycleGenerator.h#L52

**Comment by MiladShafiee** [comment]
I think `switchOverSwingRatio` is related to the `(SS/DS)` that actually regulate the amount of `DS `and `SS` based on the impact time that comes from Unicycle Planner. However the $\alpha$ is related to the amount of distribution of `DS` amount to previous and next single support time.

**Comment by S-Dafarra** [comment]
They coincide given our implementation of the DCM trajectory generator.

**Comment by MiladShafiee** [comment]
> In fact, inside this generator, the single support phase starts at the foot impact time and ends at the other foot impact time. The difference between the two impact times corresponds to a full step. That parameter determines how much of this full step has to be considered as double support (after some basic math).

I think it is one another problem that is related to coupling of the DCM planner and footstep planner. I think $\alpha$ should be a independent parameters inside the DCM planner. Probably we can discuss about this when we want to refactor these components.

**Comment by S-Dafarra** [comment]
> I think it is one another problem that is related to coupling of the DCM planner and footstep planner.

To be honest, I don't understand why. They both define the amount of a step in which both feet are on the ground. Why do you think they should be separated?

**Comment by MiladShafiee** [comment]
we have two independent value in DCM planner(without thinking about footstep planner).
First we have only single support phase, then we want to have a double support phase, because generally DCM dynamic is for single support phase. Then we say, we need also some double support phase. So we select a value for that. Then this value will be allocated from next single support phase and previous single support phase. How much should be allocated by next single support?how much should be allocated by previous single support? These values will be specified by the $alpha$ parameter.  
In my opinion, his is the way that how DCM planner should work.

**Comment by S-Dafarra** [comment]
> Then we say, we need also some double support phase. So we select a value for that. Then this value will be allocated by the next single support phase and the previous single support phase.

This is exactly the same reasoning behind the parameter ``switchOverSwingRatio``. In addition, I believe that the definition of the phases is part of the *footstep planner*. The trajectory generators, like the DCM planner, should only *use* this information, not define it.

**Comment by MiladShafiee** [comment]
> his is exactly the same reasoning behind the parameter switchOverSwingRatio

The problem is that in the current implementation I don't see how we can play with the $\alpha$ parameter. This parameter is a design variable for trajectory, but I think in our implementation it has been found automatically based on `switchOverSwingRatio`. Anyway I think we can discuss F2F about this problem.

**Comment by GiulioRomualdi** [comment]
Recap of the T2T discussion (@MiladShafiee @S-Dafarra )

First of all, it is important to remember that `alpha` is a parameter already used in [**Trajectory generation for continuous leg forces during double support and heel-to-toe shift based on divergent component of motion**](https://ieeexplore.ieee.org/abstract/document/6943128).  To understand the meaning of this parameter is important to recall that the DCM dynamics is defined only for single support and our  DCM planner is an algorithm composed of two steps:
1. We assume that the walking sequence is composed of only single support phases and the DCM is computed accordingly 
2. We use the DCM computed in the previous step to compute the DCM for double support.

The parameter `alpha` becomes important for computing the first step of the algorithm. Indeed the unicycle planner generates a vector composed by a sequence of single and double supports 
This sequence has to be reduced to a sequence of only single support trajectories. The parameter `alpha` is then used to decide how to split the double support phase. 

The following diagram should help you to understand the concept. The orange segment represents the Double Support phase while the green one the Single Support phase.
![](https://user-images.githubusercontent.com/16744101/35397127-efbfa0a8-01ee-11e8-8eb1-897c9458c5ce.png)

`t0` is the time instant in which we assume that the previous Single support ends and the new single support starts (please remember this is used only for the step 1. of the algorithm). 
`alpha` is a real number that goes from 0 to 1. If `alpha` is equal to:
- 0.5: `t0` will be in the middle of the orange segment
- 0: `t0` will be coincident to `impactTime`
- 1: `t0` will be coincident to `startTime`


In our code `alpha` is equal to 0.5 and it can be seen in 
https://github.com/robotology/unicycle-footstep-planner/blob/fd10aae80e244feeba8f8c669181d1cad4e7f9a2/src/DCMTrajectoryGeneratorHelper.cpp#L830

Changing this line adding a custom `alpha` should be enough for closing the issue

@MiladShafiee feel free to open a PR with the modification and contact me for any problem/doubt.

**Comment by MiladShafiee** [comment]
Corresponding pull request. #36

**Comment by MiladShafiee** [comment]
Since the pull request has been merged we close this issue.
