### ISSUE TITLE
Massive history modification of the repo

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/unicycle-footstep-planner#6]
Hi all,
I am changing the history of the repo to remove some big files I used in the README. I did not realize how dumb was the idea in a first place. I also taking the occasion to rebase all the branches over ``master``.

@jeljaik @GiulioRomualdi @traversaro @gabrielenava

**Comment by S-Dafarra** [comment]
Done!
It may be better to clone again the repo. Please report here any problem.

**Comment by traversaro** [comment]
Also other user of the ***-superbuild : @triccyx @prashanth05 .

**Comment by S-Dafarra** [comment]
Actually it is **highly recommended** to ``clone`` again the repo. Sorry for the inconvenience.
